name: 'Flyway Migrate'
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Flyway Migrate
        uses: docker://redgate/flyway:10
        with:
          args: >-
            migrate
            -workingDirectory="/github/workspace/"
            -url="${{ secrets.DATABRICKS_JDBC_URL }}"
            -user="${{ secrets.DATABRICKS_USER }}"
            -password="${{ secrets.DATABRICKS_TOKEN }}"